---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
```


## Connect to existing chrome

+ https://medium.com/@jaredpotter1/connecting-puppeteer-to-existing-chrome-window-8a10828149e0


```{r}
library(tidyverse)
reticulate::use_python("/usr/local/bin/python3")
library(reticulate)
source_python("page.py")
```



```{r}
# launch_chrome_mac()


chrome <- browser$new(debug_port = 9222)

tabs <- chrome$list_tabs()

target_title <- tabs %>%
  dplyr::filter(stringr::str_detect(url, "ringGameTable")) %>%
  dplyr::pull(title)
e <- c()

while(T){
  e <- c(e, Sys.time())
  a <- chrome$execute(target_title[1], 'document.querySelector(".table_page").innerHTML')
}
tiktokr::from_unix(e)

Vget_tabs()

e %>%
  purrr::reduce(c) %>%
  tibble::tibble(source = .)

# source_python('https://gist.githubusercontent.com/benjaminguinaudeau/99e03118a1208280b7e6921d5a1f9549/raw/49eb06c9a44acc7a88ac62e6de269c5c5f6e4021/poker.py')


```

+ new_tab
+ 


```{r}

tabs <- get_tabs() %>%
  glimpse

tab_target <- tabs$title[1]
``` 


```{python}



 

```


```{r}



endpoint <- launch_chrome()
tabs <- py$get_tabs(endpoint)

response <- py$execute(endpoint, tab, script)

get_table <- function(endpoint, tab_name){
  py$execute(endpoint, tab_name, script = 'document.querySelector(".table_page").innerHTML')
}

action_fold  

pok <- py$poker(out$webSocketDebuggerUrl)
pok$source



```


```{node}

const { chromium } = require('playwright');

const create_server = async () => {
  const browserServer = await chromium.launchServer({ headless: false, slowMo: 50 });
  const wsEndpoint = browserServer.wsEndpoint();
  console.log(wsEndpoint)
  // Use web socket endpoint later to establish a connection.
   const browser = await chromium.connect({ wsEndpoint });
  // Close browser instance.
  // await browserServer.close();
  return wsEndpoint
}

const ep = create_server();

ep.then(ep => {
  return chromium.connect({ wsEndpoint: ep,}).then(browser => {
    const a = browser.newPage().then(page => {
      return page.goto('http://whatsmyuseragent.org/').then(site => {
        return page.content().then(a => {
          return page
        })
      })
    });
    return browser.newPage().then(page => {
      return page.goto('http://whatsmyuseragent.or').then(site => {
        return page.content().then(a => {
          return page
        })
      })
    })
  })
  
  
})

const conne = async () => {
  //console.log(ep);
  const endpoint = await ep
  console.log(endpoint);
  //const browser = await chromium.connect({ endpoint });
}

ep.then(connect(ep))

()(ep);


(async (ep) => {
  const browser = await chromium.connect({'ws://127.0.0.1:62053/1a157ed0d6e2d91dcd6b8f76275323e5'});
  const page = browser.newPage() ;
  page.goto('http://whatsmyuseragent.org/') ;
})(ep);

const browse = () => {
  
  return chromium.launch({ headless: false, slowMo: 50 }).then(browser => {
    console.log(browser.wsEndpoint());
    return browser.newPage().then(page => {
      return page.goto('http://whatsmyuseragent.org/').then(site => {
        return page.content().then(a => {
          return page
        })
      })
    })
  })
}
d = browse()


const browse = () => {
  return chromium.launch({ headless: false, slowMo: 50 }).then(browser => {
    console.log(browser.wsEndpoint());
    return browser.newPage().then(page => {
      return page.goto('http://whatsmyuseragent.org/').then(site => {
        return page.content().then(a => {
          return page
        })
      })
    })
  })
}
d = browse()
          # console.log('My object : ' + a);
const test = d.then(page => {
  const brow
  return browser.newPage().then(page => {
      return page.goto('http://twitter.org/').then(site => {
        return page.content().then(a => {
          console.log('My object : ' + a);
          return a
        })
      })
    })
})


```

```{r}
library(tidyverse)

c("AS AC", "AC KC") %>% 
  stringr::str_detect(".(?=\\s|$)") %>% 
  map_lgl(~.x[1] == .x[2])

card_comb <- function(a, b) return(glue::glue("(?=({a}. )?){b}(?=(. {a}.)?)"))
paar <- function(a) return(glue::glue("{a}. {a}."))
regex <- paste(c(paar("7"), paar("6"), card_comb("K", "10"), card_comb("Q", "10")), collapse = "|")

c("AS AC", "AC KC", "KC 10C", "10C K10") %>% 
  str_replace("(S(?= .*?S))|(C(?= .*?C))|(H(?= .*?H))|(D(?= .*?D))", "a") %>%
  str_detect(glue::glue("(A|{paar('7')}|{paar('6')}|card_comb()
  (?=(10. )?)K(?=(. 10.)?)|Q. 10.|10. Q.|J. 10.|10. J.|K. 9.|9. K.)|
             ((Aa.*?|a A.$|Ka 10.|10a K.|Qa 10.|10a Q.|Ja 10.|10a J.|Ka 9.|9a K.))")



one_of <- function(a, b = NULL){
  if(is.null(b)){
    regex <- glue::glue("({a}?S {a}?S)|({a}?C {a}C)|({a}?H {a}?H)|({a}?D {a}?D)")
  }
  
}

t <- haven::read_dta("https://cloud.uni-konstanz.de/index.php/s/fg45gEywyTFsbTA/download")

```


```{r}

const { webkit } = require('playwright');

async function browser() {
  const browser = await webkit.launch();
  const page = await browser.newPage();
  await page.goto('http://whatsmyuseragent.org/');
  const a = await page.content();
  return a;
}

async function foo() {
    return 42;
}



async function brow() {
  const browser = await webkit.launch();
  const page = await browser.newPage();
  await page.goto('http://whatsmyuseragent.org/');
  const a = await page.content();
  console.log('My object : ' + a);
  return browser;
}

brow().then(result => {
  (async () => {
  const page = await result.newPage();
  await page.goto('http://twitter.com/');
  const a = await page.content();
  console.log('My object : ' + a);
  })
})
})

(async(brow) => {
  const page = await brow.newPage();
  await page.goto('http://twitter.com/');
  const a = await page.content();
  console.log('My object : ' + a);
})(e)



const test = async () => {
  const browser = await webkit.launch();
  const page = await browser.newPage();
  await page.goto('http://whatsmyuseragent.org/');
  const a = await page.content();
  console.log('My object : ' + a);
  return webkit
}

const broser2 = async (browser) => {
  const page = await browser.newPage();
  await page.goto('http://twitter.com/');
  const a = await page.content();
  console.log('My object : ' + a);
  return browser
}

br = (async () => {
  const browser = await webkit.launch();
  const page = await browser.newPage();
  await page.goto('http://whatsmyuseragent.org/');
  const a = await page.content();
  console.log('My object : ' + a);
  await page.goto('http://facebook.com');
  const b = await page.content();
  console.log('My object : ' + b);
  await page.screenshot({ path: `example.png` });
  return browser
})();

(async (br) => {
  const page = await br.newPage();
  await page.goto('http://whatsmyuseragent.org/');
  const a = await page.content();
  console.log('My object : ' + a);
})(br);

  # await browser.close();

  # print a
(async () => {
  const browser = await webkit.launch();
  await page.goto('http://facebook.com/');
  await page.screenshot({ path: `face.png` });
  await browser.close();
})();
  

```

