---
title: "simons"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
reticulate::use_condaenv("pw", required = TRUE)
options(python_init = TRUE)
library(reticulate)
```

```{r}
library(tidyverse)
library(rvest)
devtools::load_all()
```


```{r}
click_link <- function(link){
  page$query_selector(".main_menu_dropdown_title")$hover()
  title <- page$query_selector(glue::glue("a[href = '{link}']"))
  title$click()
  
}

check_subscription_box <- function(page){
  if(length(page$query_selector("#newsletter_fancybox_content")) > 0){
    page$keyboard$press("Escape")
  }
}

check_quick_view <- function(page){
  if(length(page$query_selector("#fancybox-close")) > 0){
    page$keyboard$press("Escape")
  }
}

get_size <- function(page){
  page$query_selector(".sizes")$query_selector_all(".button_mini") %>% 
    map_chr(~{
      if(str_detect(.x$get_attribute("class"), "disabled")) return("")
      .x$text_content()
      
    }) %>%
    discard(~.x == "") %>%
    str_trim %>%
    str_split(pattern = "\\s+") %>%
    unlist
}

get_imgs <- function(page){
  page$query_selector("#product_left")$query_selector_all("img") %>%
    map_chr(~.x$get_attribute("src")) %>%
    unique
}



get_quick_details <- function(card){
  
  id <- card %>% html_attr("id")
  link <- card %>% html_node("a[href]") %>% html_attr("href")
  pic <- card %>% html_nodes("img") %>% html_attr("src") %>% unique
  desc <- card %>% html_node(".desc") %>% html_text(trim = T)
  brand <- card %>% html_node(".brand") %>% html_text(trim = T)
  offers <- card %>% 
    html_nodes("span[itemprop='offers']") %>% 
    html_text(trim = T) %>%
    str_split("\\s+")
  
  elem <- page$query_selector(glue::glue('div[data-uid="{id}-"]'))
  if(length(elem) == 0){
    elem <- page$query_selector(glue::glue('div[data-uid="{id}-0"]'))
  }
  page %>% check_quick_view()
  elem$hover()
  elem$query_selector(".quick")$click()
  page %>% check_subscription_box()
  Sys.sleep(.1)
  page$wait_for_selector("#product_left", timeout= 10000)
  page$wait_for_load_state()
  size_imgs <- page$query_selector(".swatches_fieldset")$query_selector_all("a") %>%
    map_dfr(~{
      .x$click()
      page$wait_for_load_state()
      
      size <- page %>% get_size()
      imgs <- page %>% get_imgs()
      tibble::tibble(size = list(size), imgs = list(imgs))
      
    })
  
  page$keyboard$press("Escape")
  
  tibble::tibble(id = id, link = link, pic = list(pic), desc = desc, brand = brand, price = offers) %>%
    bind_cols(size_imgs)
  
  
}
```



```{r}
chrome <- new_browser("chrome", headless = F)
page <- chrome$pages[[1]]
page$goto("https://simons.ca")

content <- page$content() %>%
  xml2::read_html()

links <- content %>%
  html_nodes(".main_menu_extend_column") %>%
  map(~{
    .x %>% 
      html_nodes("a[href]") %>%
      html_attr("href")
  }) %>%
  reduce(c) %>%
  unique %>%
  str_subset("simons.ca") %>%
  str_subset("(sale--sale)|(men-(clothing|accessories)/[^\\/]+$)")

link <- links[3]
click_link(link)
if(page$locator('text="View 300 per page"')$count() > 0) page$locator('text="View 300 per page"')$first$click()

a <- page$locator('text="View 300 per page"')


```


```{r}
chrome <- new_browser("chrome", headless = F)
page <- chrome$pages[[1]]

page %>% goto("https://www.simons.ca/en/men-clothing/sale--sale-6714")



cards <- page$content() %>%
  xml2::read_html() %>% 
  rvest::html_nodes(".product_card")

url <- page$url
base_dest <- paste0(lubridate::today("UTC"), "/", str_extract(url, "[^\\/]*?$"), "/")

cards %>% #bashR::simule_map(1)
  imap_dfr(~{
    Sys.sleep(runif(1, 0, 5))
    
    dest <- paste0(base_dest, html_attr(.x, "id"), ".rds")
  
    print(.y)
    if(!fs::file_exists(dest)){
      out <- get_quick_details(.x) %>% glimpse
      write_rs(out, dest)
    }
  })

card <- c <- sample(cards, 1)
out <- get_quick_details(c)
out$imgs[[1]] %>% walk(browseURL)
out$size[[1]]
card <- c
```


